name: lint

on:
  push: {}
  pull_request: {}
  schedule:
    # 8AM first day of the month
    - cron: "0 8 1 * *"

jobs:
  feature-matrix:
    uses: ./.github/workflows/feature-matrix.yaml

  lint:
    name: lint ${{ matrix.package.name }} (features ${{ matrix.package.features }})
    runs-on: ubuntu-24.04
    needs: [feature-matrix]
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.feature-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Lint
        # prettier-ignore
        run: >-
          task lint --
          --package "${{ matrix.package.name }}"
          --features "${{ matrix.package.features }}"

  audit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: dtolnay/rust-toolchain@stable
      - run: brew install cargo-audit
      - name: Audit
        run: task audit

  outdated:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-outdated
      - name: Check for outdated dependencies
        run: task outdated

  unused-dependencies:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: dtolnay/rust-toolchain@nightly
      - run: brew install cargo-udeps
      - name: Check for outdated dependencies
        run: task unused-dependencies

  spellcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: dtolnay/rust-toolchain@stable
      - run: brew install typos-cli
      - name: Spellcheck
        run: task spellcheck
